- name: Playbook to release laravel (Store/Service)
  hosts: myservers
  become: yes
  tasks:

    - name: Set deploy dir
      set_fact:
        release_dir: "/var/www/ARCVService/releases/ARCVService-{{ tag }}"

    - name: Ensure release dir
      file:
        path: "{{ release_dir }}"
        state: directory
      become: yes

    - name: Get release
      get_url:
        url: https://github.com/neontribe/ARCVService/archive/refs/tags/{{ tag }}.tar.gz
        dest: /tmp/release-{{ tag }}.tgz
        mode: '0664'

    - name: Unpack release
      unarchive:
        src: /tmp/release-{{ tag }}.tgz
        dest: "{{ release_dir }}"
        extra_opts:
          - "--strip-components=1"
        remote_src: yes

    - name: Clean up un-needed files
      file:
        path: "{{ release_dir }}/{{ item }}"
        state: absent
      with_items:
        - .docker
        - docker-compose.yml
        - Dockerfile
        - Docker.md
        - env.example
        - env.travis
        - .gitattributes
        - .gitignore
        - INSTALL.md
        - makedeploy.sh
        - Makefile
        - phpunit.xml
        - README.md
        - staging_rsa.enc
        - UPGRADE_NOTES.md
        - tests
        - .travis.yml

    - name: Ensure storage dirs
      file:
        path: "{{ release_dir }}/{{ item }}"
        state: directory
      with_items:
        - storage/app
        - storage/framework/cache
        - storage/framework/views
        - storage/framework/sessions
        - storage/logs

    - name: Composer install
      composer:
        command: install
        working_dir: "{{ release_dir }}"
        arguments: --no-ansi
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1

    - name: Add yarn install wrapper script
      copy:
        src: assets/yarn-wrapper.sh
        dest: "{{ release_dir }}/yarn-wrapper.sh"
        group: root
        owner: root
        mode: 0755

    - name: Yarn install and build
      shell: docker run -v "{{ release_dir }}":/build:Z --entrypoint /build/yarn-wrapper.sh node:20
      args:
        executable: /bin/bash
        chdir: "{{ release_dir }}"

    - name: Clean up node modules and helper script
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ release_dir }}/yarn-wrapper.sh"
        - "{{ release_dir }}/node_modules"

    - name: Update version.txt
      shell: "echo {{ tag }} > version.txt"
      args:
        executable: /bin/bash
        chdir: "{{ release_dir }}"

    - name: Ensure ownership (web)
      file:
        dest: "{{ release_dir }}"
        owner: "{{ webuser }}"
        group: "{{ webuser }}"
        mode: u=rwX,g=rwX,o=rX
        recurse: yes
      become: yes

    - name: Fix selinux context
      sefcontext:
        target: '/var/www(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present

    - name: Restore se linux context just in case
      shell: restorecon -R "{{ release_dir }}"

