
- import_playbook: dump-db.yml

- name: Playbook to release laravel (Store/Service)
  hosts: myservers
  become: yes

  tasks:

    - name: Set deploy dir
      set_fact:
        release_dir: "/var/www/ARCVService/releases/ARCVService-{{ tag }}"

    - name: Clear storage directory
      file:
        state: absent
        path: "{{ release_dir }}/storage"
      become: yes

    - name: Link in .env
      file:
        state: link
        src: /var/www/ARCVService/service_env
        dest: "{{ release_dir }}/.env"
      become: yes

    - name: Link in storage
      file:
        state: link
        src: /var/www/ARCVService/storage
        dest: "{{ release_dir }}/storage"
      become: yes

    - name: Generate assets
      shell: yarn production
      args:
        executable: /bin/bash
        chdir: "{{ release_dir }}"
      become: yes

    - name: Link current_release
      file:
        state: link
        force: true
        src: "{{ release_dir }}"
        dest: /var/www/ARCVService/current_release
      become: yes

    - name: Link public_html
      file:
        state: link
        force: true
        src: "{{ release_dir }}/public"
        dest: /var/www/ARCVService/public_html
      become: yes

    - name: Run migrations
      shell: php artisan migrate --force
      args:
        executable: /bin/bash
        chdir: /var/www/ARCVService/current_release
      become: yes

    - name: Cache clear, Config clear, Optimise
      shell: php artisan {{ item }}
      args:
        executable: /bin/bash
        chdir: /var/www/ARCVService/current_release
      with_items:
        - cache:clear
        - config:clear
        - optimize:clear
        - view:clear
        - clear-compiled
      become: yes

    - name: Ensure folder ownership (web)
      file:
        dest: /var/www/ARCVService/{{ item }}
        owner: "{{ webuser }}"
        group: "{{ webuser }}"
        mode: u=rwX,g=rX,o=rX
        recurse: yes
      become: yes
      with_items:
        - storage
        - current_release/bootstrap
        - "{{ release_dir }}/bootstrap"
        - "{{ release_dir }}/storage"

    - name: Ensure .env ownership (web)
      file:
        dest: "{{ item }}"
        owner: "{{ webuser }}"
        group: "{{ webuser }}"
        mode: u=rwX,g=rwX,o=rX
      become: yes
      with_items:
        - "{{ release_dir }}/version.txt"
        - "{{ release_dir }}/storage"

    - name: Restart supervisord, httpd, fpm
      service:
        name: "{{ item }}"
        state: restarted
      become: yes
      with_items:
        - supervisord
        - httpd
        - php-fpm

    # restorecon -R /var/www/
